use_frameworks!

platform :ios, '10.0'

target 'WidgetCollection-Swift_Example' do
  pod 'WidgetCollection-Swift', :path => '../'

  target 'WidgetCollection-Swift_Tests' do
    inherit! :search_paths

    
  end
end
